### ISSUE TITLE
Error Building Tests

### ISSUE THREAD

**Issue by matt-stack** [lanl/singularity-eos#11]
Hello, I recently pulled upstream to my fork, and found my trusty build command resulted in the following error during build:

/home/singularity-eos/test/eos_unit_tests.cpp(196): error: identifier "steelID" is undefined
... and a few more variables undefined

And saw that in eos_unit_tests.cpp, the variables definitions were surrounded by preprocessor flags:
#ifdef SPINER_USE_HDF
#ifdef SPINER_TEST_SESAME
constexpr int steelID = 4272;
constexpr int airID = 5030;
constexpr int DTID = 5267;
constexpr int goldID = 2700;
constexpr Real ev2k = 1.160451812e4;
#endif // SPINER_TEST_SESAME
#endif // SPINER_USE_HDF

In my case, I grep'ed around for SPINER_TEST_SESAME but could not find it defined. I changed it to #ifdef SINGULARITY_TEST_SESAME and the build finished with no errors. I think it may be a tiny mistake, considering that I couldn't find any other reference to SPINER_TEST_SESAME in the repo and further down in the same eos_unit_test file it is in this same format that I changed to:
#ifdef SPINER_USE_HDF
#ifdef SINGULARITY_TEST_SESAME

**Comment by Yurlungur** [comment]
Yep this is a typo-induced bug. Thanks for the catch! I saw your pull request, and I'll merge it in as soon as tests pass.

By the way, thanks for contributing to the project! If you're able to share, I'd love to hear what you're doing with the project downstream. I just created an issue, #13 to discuss.
