### ISSUE TITLE
`#error "Eigen should not be used with Kokkos"`

### ISSUE THREAD

**Issue by mauneyc-LANL** [lanl/singularity-eos#125]
The following setup seems common enough:

```cmake
set(SINGULARITY_USE_KOKKOS ON)
set(SINGULARITY_USE_KOKKOSKERNELS OFF)
```

Without `kokkoskernels`, the library defaults to using `Eigen` as the LA backend. However, in `singularity-eos/closure/mixed_cell_models.hpp:123` there is

```c
#error "Eigen should not be used with Kokkos"
```

My understanding is that Eigen + Kokkos is okay, but Eigen + Kokkos + CUDA is what should be avoided; if so, then the check should be for Eigen + CUDA, without reference to kokkos. In any event, we should clear up the configuration of when Eigen is used, and when it is not used and do this in the CMake configuration. The preprocessor line is then redundant.

**Comment by mauneyc-LANL** [comment]
This looks to be removed in `main`, closing.

**Comment by mauneyc-LANL** [comment]
Addressed build failures in !126, but not clear to me if this has been resolved.

**Comment by Yurlungur** [comment]
:+1: Let's close the issue for now then and re-open if needed.
