### ISSUE TITLE
Build issues without cmake

### ISSUE THREAD

**Issue by Yurlungur** [lanl/singularity-eos#139]
@chadmeyer brought to my attention that it seems to be difficult to build a program that depends on `singularity-eos` after installing it without relying on `cmake`. In particular:
```bash
gcc -I../singularity-eos/build/include -I../singularity-eos/utils/eigen -L../singularity-eos/build/lib -lsingularity-eos -leos -lstdc++ -lm test_pte.cpp
```
fails with linker errors of the form
```bash
/tmp/ccvgExfc.o: In function `singularity::RelativisticEOS<singularity::IdealGas>::PressureFromDensityTemperature(double, double, double*) const':
test_pte.cpp:(.text._ZNK11singularity15RelativisticEOSINS_8IdealGasEE30PressureFromDensityTemperatureEddPd[_ZNK11singularity15RelativisticEOSINS_8IdealGasEE30PressureFromDensityTemperatureEddPd]+0x3b): undefined reference to `singularity::IdealGas::PressureFromDensityTemperature(double, double, double*) const'
```
@mauneyc-LANL do you have any ideas? Maybe your rewrite just fixes all this.

**Comment by mauneyc-LANL** [comment]
Does changing the order of `-lsingularity-eos` `-leos` make any difference?

**Comment by chadmeyer** [comment]
No difference.

**Comment by chadmeyer** [comment]
Wait, ` g++ -I../singularity-eos/build/include -I../singularity-eos/utils/eigen -L../singularity-eos/build/lib test_pte.cpp -leos -lsingularity-eos` will link.

**Comment by chadmeyer** [comment]
Nevertheless, Eigen is not being installed in a way consistent with the header-only implementation of the PTE solver.

**Comment by Yurlungur** [comment]
Glad `g++` works. I'm leaving this open so we can make sure the installation of dependencies is handled appropriately.

**Comment by chadmeyer** [comment]
It wasn't g++/gcc it was actually putting the libraries *after* the source code...

**Comment by Yurlungur** [comment]
Ah ok. Well, glad it's resolved.

**Comment by mauneyc-LANL** [comment]
> Nevertheless, Eigen is not being installed in a way consistent with the header-only implementation of the PTE solver.

Can you clarify the context here? If not using `cmake` to configure the build, then handling the `eigen` dependency has to be done manually (e.g. hand-writting paths in a `Makefile`).

`eigen` uses a `cmake` install as standard, and by default will configure to include tests/examples in the install manifest. These can be disabled with `cmake` options at configuration, but regardless the core `eigen` library remains a header-only and will be installed into `<eigen_install_prefix>/include`.

It's also supported to just copy the `eigen` headers into whatever install directory by hand. The current `main` branch `cmake` install does this. The pending CMake updates use the `cmake` configuration distributed with `Eigen`, and sets the options to only install header files.

**Comment by mauneyc-LANL** [comment]
> @mauneyc-LANL do you have any ideas? Maybe your rewrite just fixes all this.

The pending changes produce only a `libsingularity-eos.a` (`eospac-wrapper` is considered a separate library)

**Comment by dholladay00** [comment]
can we close this @mauneyc-LANL @Yurlungur ?

**Comment by Yurlungur** [comment]
Closing. We can re-open as needed.
