### ISSUE TITLE
Break out unrelated tests from the FastMath test

### ISSUE THREAD

**Issue by jhp-lanl** [lanl/singularity-eos#147]
It looks like a bunch of the tests under the `FastMath` scenario have nothing to do with the fast logarithms even if they're grouped there. I think these should be broken out of this scenario into more relevant groupings

_Originally posted by @jhp-lanl in https://github.com/lanl/singularity-eos/pull/101#discussion_r911507796_

**Comment by Yurlungur** [comment]
Resolved in the ctest/testing refactor.
