### ISSUE TITLE
Missing header in ramps_eos.hpp

### ISSUE THREAD

**Issue by jdolence** [lanl/singularity-eos#149]
I think the header pointing to the root finder is missing in `ramps_eos.hpp`.  Needs something like

```c++
#include <singularity-eos/base/root-finding-1d/root_finding.hpp>
```

@dholladay00

**Comment by dholladay00** [comment]
This confused me as well, but I believe it passed the tests b/c the only place the function template is instantiated is in singularity_eos.cpp, a translation unit which includes eos.hpp which includes the root find header.
