### ISSUE TITLE
Make spiner an optional dependency

### ISSUE THREAD

**Issue by jhp-lanl** [lanl/singularity-eos#184]
@Yurlungur @jonahm-LANL @mauneyc-LANL 

Although the spiner code won't be compiled unless the `SPINER_USE_HDF` flag is on, it sounds like spiner is still a required part of the build chain. In talking with @mauneyc-LANL this means that spiner is _technically_ a required dependency in singularity even if that wasn't the intent.

Talking with @mauneyc-LANL, my impression also is that the HDF5 dependency is a bit confusing as well when this is really just required for spiner.

**Comment by jhp-lanl** [comment]
@dholladay00

**Comment by Yurlungur** [comment]
Resolved.
