### ISSUE TITLE
Tranisition to C++17

### ISSUE THREAD

**Issue by mauneyc-LANL** [lanl/singularity-eos#185]
It appears that `kokkos` is requiring C++17 moving into the next major version (https://github.com/kokkos/kokkos/issues/5439). As a result, some of our downstream codes are planning moves to C++17 as well. 

I'm creating this as an issue to coordinate discussion and plans, if any.

**Comment by Yurlungur** [comment]
TODOS:
- [ ] as soon as xrage is on C++17 so are we
- [ ] Build system will need to say C++17
- [ ] We will check that std::variant works on device and remove the mpark backport as soon as we can

**Comment by Yurlungur** [comment]
Resolved.
