### ISSUE TITLE
MPI on cray machines

### ISSUE THREAD

**Issue by cmauney** [lanl/singularity-eos#189]
During the Hackathon, @dholladay00 found that MPI dependency gets confused when rebuilding with hipcc. This may be due to `cmake` lacking capability for the cray system using `hipcc`, though it will be worth testing on other cray machines where `cmake` can handle the existing cray environment.

**Comment by Yurlungur** [comment]
I believe we encountered this issue in Parthenon. @pgrete could say more on the topic.

**Comment by Yurlungur** [comment]
Now resolved. Tested in our build matrix.
