### ISSUE TITLE
missing headers

### ISSUE THREAD

**Issue by dholladay00** [lanl/singularity-eos#227]
@mauneyc-LANL, @Yurlungur, it looks like the cmake variable `EOS_HEADERS` is missing `eos_base.hpp` and `variadic_utils.hpp`. Installed versions of singularity-eos trying to use the native c++ API have missing header issues. Perhaps unrelated, but James was also seeing an issue with multiple portability strategies being defined. First step first though.

**Comment by Yurlungur** [comment]
the multiple portability thing might be because of cmake storing previous installs in `~/.cmake`

Oof ok let's make sure that those two header files get added

**Comment by mauneyc-LANL** [comment]
Fixed by #228

**Comment by dholladay00** [comment]
eospac wrapper is not included @mauneyc-LANL
