### ISSUE TITLE
PTE Solver produces an FPE for EOS that rely on default RhoPmin() behavior

### ISSUE THREAD

**Issue by jhp-lanl** [lanl/singularity-eos#354]
Most EOS don't define `RhoPmin()` and thus rely on the behavior defined in the base class:
```c++
  PORTABLE_INLINE_FUNCTION
  Real RhoPmin(const Real temp) const { return 0.0; }
```

The issue is that in the  PTE solver we have the following:
```c++
  PORTABLE_FORCEINLINE_FUNCTION
  void SetVfracFromT(const Real T) {
    Real vsum = 0.0;
    // set volume fractions
    for (int m = 0; m < nmat; ++m) {
      const Real rho_min = eos[m].RhoPmin(T);
      const Real vmax = std::min(0.9 * rhobar[m] / rho_min, 1.0);
      vfrac[m] = (vfrac[m] > 0.0 ? std::min(vmax, vfrac[m]) : vmax);
      vsum += vfrac[m];
    }
    // Normalize vfrac
    for (int m = 0; m < nmat; ++m) {
      vfrac[m] *= vfrac_total / vsum;
    }
  }
```
where we _divide_ by the result of `RhoPmin(T)`.

I'm not quite sure how this hasn't gone unnoticed before now. @jonahm-LANL do you have any insight into why this wasn't triggering undefined behavior in other codes?

I think we need to add divide by zero guards all over the PTE solver, and it's also possible that we should rethink the default return value for `RhoPmin()`.

**Comment by jhp-lanl** [comment]
I'm just going to go through the PTE solver and try to find all the possible FPEs I can while also sticking in some asserts so we can catch more edge cases when compiling in debug.

For example, I just found another possible FPE:
```c++
  PORTABLE_INLINE_FUNCTION
  void InitBase() {
    ...
    uscale = rho_total * sie_total;
    ...
    // note the scaling of the material internal energy densities
    for (int m = 0; m < nmat; ++m)
      u[m] = sie[m] * rhobar[m] / uscale;
  }
```

It looks like there's an assumption here that `uscale` is always positive when it can be zero or negative. I think it's appropriate to stick in both a robust ratio as well as an absolute value.

**Comment by Yurlungur** [comment]
> I'm not quite sure how this hasn't gone unnoticed before now. @jonahm-LANL do you have any insight into why this wasn't triggering undefined behavior in other codes?

The `std::min` there is probably saving us. But yeah, should be `robust::ratio`.

I'm in favor of adding guard rails here.
