### ISSUE TITLE
some quick comments on a vector interface

### ISSUE THREAD

**Issue by Yurlungur** [lanl/singularity-eos#36]
This briefly summarizes discussions had with @annapiegra @dholladay00 and @jhp-lanl .

## Vector API

A vector API is desired---likely (for now) called host-only. The pattern is for a function
```C++
PORTABLE_FUNCTION Real Foo(Real input1, Real input2, Real* lambda);
```
we add a function
```C++
template<typename RealIndexer, typename LambdaIndexer>
inline void Foo(RealIndexer&& input1, RealIndexer&& input2, RealIndexer&& output, int n, LambdaIndexer&& lambda);
```
that can be implemented per-eos.

## PTE solvers

If a vector API becomes available, we can also look at doing PTE solves on vectors instead of on scalars.
- [ ] A first step would be to abstract as much of the inner machinery of the solver as possible into re-usable functions
- [ ] A second step would be to implement a version of the PTE solver that uses vectors
- [ ] A key piece will be thinking about memory allocation. We may need a way to provide a block of memory that the solver can use so that we only allocate scratch memory that scales as the number of threads, rather than as the number of elements of the vector

**Comment by dholladay00** [comment]
I think it should be:
```c++
template<typename T, typename U>
inline void Foo(T&& var1_indexer, T&& var2_indexer, int n, U&& lambda_indexer)
```

**Comment by Yurlungur** [comment]
you are right. Edited for posterity.

**Comment by jhp-lanl** [comment]
I think I can volunteer to tackle that first step here next week since I see it being fairly straight-forward. We'll see though!

**Comment by Yurlungur** [comment]
> I think I can volunteer to tackle that first step here next week since I see it being fairly straight-forward. We'll see though!

I think it'll be straightforward. Happy to get you started with pair programming too.

**Comment by jhp-lanl** [comment]
> > I think I can volunteer to tackle that first step here next week since I see it being fairly straight-forward. We'll see though!
> 
> I think it'll be straightforward. Happy to get you started with pair programming too.

Let me dive in early next week and I'll hit you up when I have questions and troubles.

**Comment by jhp-lanl** [comment]
closing since we have a vector API that I think satisfies these requirements. Vectorizing the PTE solve is still a goal, but I think that can be rolled into improvements for EOSPAC.
