### ISSUE TITLE
Gibbs Free Energy

### ISSUE THREAD

**Issue by Yurlungur** [lanl/singularity-eos#397]
Given we have an entropy call, it seems relatively trivial now to add a Gibbs free energy call to the EOS base class that automatically converts between potentials.

$$G(\rho, T) = \varepsilon(\rho, T) + \frac{P(\rho, T)}{\rho} - T S(\rho, T)$$

**Comment by jhp-lanl** [comment]
That's fine with me. We can also think about the density-energy call too:
```math
G(\rho, \epsilon) = \epsilon + \frac{P(\rho, \epsilon)}{\rho} - T(\rho, \epsilon) S(\rho, \epsilon)
```
