### ISSUE TITLE
In-tree builds fail on venado

### ISSUE THREAD

**Issue by Yurlungur** [lanl/singularity-eos#404]
I'm not sure we need to fix this yet, given how unstable venado is. But the hdf5 logic that gets skipped when building in-tree on cray systems is improperly getting run on Venado, causing cmake to fail. @mauneyc-LANL

**Comment by cmauney** [comment]
Can you be more specific? How are you building, what is the output? Are you using `-DSINGULARITY_FORCE_SUBMODULE_MODE=ON`?

**Comment by Yurlungur** [comment]
> Can you be more specific? How are you building, what is the output?

I am using the following cmake settings (this is an intree build so it actually is a submodule)
```
  set(SINGULARITY_USE_HDF5 ON CACHE BOOL "" FORCE)                                                                          
  set(SINGULARITY_USE_SPINER ON CACHE BOOL "" FORCE)    
  set(SINGULARITY_USE_KOKKOS ON CACHE BOOL "" FORCE)                                                                        
  set(SINGULARITY_USE_FORTRAN OFF CACHE BOOL "" FORCE)                                                                      
  set(SINGULARITY_FORCE_SUBMODULE_MODE ON CACHE BOOL "" FORCE)                                                                    
  set(SINGULARITY_USE_KOKKOSKERNELS ON CACHE BOOL "" FORCE)                                                                 
  set(SINGULARITY_BUILD_CLOSURE ON CACHE BOOL "" FORCE)    
```

That said, now I can't reproduce... so I'm not sure what's going on here. Disregard for now..
