### ISSUE TITLE
EOSPAC backend with serialization/deserialization

### ISSUE THREAD

**Issue by Yurlungur** [lanl/singularity-eos#408]
I am able to get the EOSPAC backend to work with serialization/deserialization and shared memory with a single instance. However in the case where eospac is constructed for multiple materials, There will be problems, because the library backend is global while an EOS object is per material. Worse, the de-serialization operation is global. There is no way to deserialize for only one material.

I am not sure what the solution to this is. We may wish to extend the EOSPAC object to load multiple materials at once. Alternatively perhaps there's a way to serialize and de-serialize a *set* of EOS objects, all at once. That could get around this problem.

**Comment by jhp-lanl** [comment]
Let's try destroying just the tables that the class owns and see what happens. We'll discuss with EOSPAC team.
