### ISSUE TITLE
Fix EOSPAC errors from calls in __host__ __device__ functions

### ISSUE THREAD

**Issue by jhp-lanl** [lanl/singularity-eos#421]
We have been a bit lazy with our `PORTABLE_INLINE_FUNCTION` calls and EOSPAC. Since EOSPAC can't be called from within a device kernel, we need to get rid of those function decorators when calling EOSPAC.

For example,
https://github.com/lanl/singularity-eos/blob/main/singularity-eos/eos/eos_eospac.hpp#L1297

fails on certain platforms with the error `error: reference to __host__ function 'eosSafeInterpolate' in __host__ __device__ function`.

**Comment by Yurlungur** [comment]
The eospac functions need to be decorated as portable_function because of the variant. But we can implement an alternative approach to resolve this issue by clever application of preprocessor macros provided by device vendors that are only true on device.

**Comment by jhp-lanl** [comment]
Ahhhhh right... the function signature needs to be _exactly_ the same. Sounds good!
