### ISSUE TITLE
Rename `Tguess` in PTE solver and document `temp[0]` usage

### ISSUE THREAD

**Issue by jhp-lanl** [lanl/singularity-eos#423]
In our PTE solvers, we actually use `temp[0]` as the starting point for the sovler (if I'm reading our code correctly). `Tguess` seems to really just be a ballpark value used to rescale the temperatures for numerical niceness.

I think we need to
1. document the usage of `temp[0]` in our PTE solvers and note that the PTE solver benefits from a sane value
2. rename `Tguess` to something that more appropriately describes its function

**Comment by jhp-lanl** [comment]
I didn't realize you were already working on this @Yurlungur ! Thanks for your MR addressing this!

**Comment by Yurlungur** [comment]
I saw your issue yesterday and I was already playing in the PTE solver for other reasons, so I just added it. :)
