### ISSUE TITLE
Expose mean atomic number and atomic weight to downstream users

### ISSUE THREAD

**Issue by chadmeyer** [lanl/singularity-eos#426]
When we're going down the road toward supporting some parts of 3T physics, downstream codes will want to query mean atomic number and mean atomic weight.  This would also be a useful pre-requisite for `singularity-eos` implementing some 3T eos support directly.

Here's how I imagine it working.
* All EOSs have some additional member variables representing `z_bar` and `a_bar`.  There is some default value (`singularity::no_atomic_number == -1.0` or something)
* Tabular EOSs (`eospac`, `spiner`) read in these quantities and set them appropriately
* Analytic EOSs either include optional arguments in their constructors or just member routines (`set_abar(const Real)`) that can be called to set the values if needed/desired.
* All EOSs have getter routines `Real get_zbar()` that return the value.  

Questions that might warrant further discussion:
* Is it possible or desirable to have some sort of optional arguments in the constructor?  Can that be inherited?  
* If an eos uses the scaling modifier, should that by default scale the mean atomic weight?

**Comment by jhp-lanl** [comment]
What is the definition of `z_bar` in this context?

**Comment by Yurlungur** [comment]
Yes `z_bar` must be average atomic number and `a_bar` average atomic mass. That said we should maybe think about how z-splitting type approaches work for a given ionization state. IMO this should be handled with modifiers.

**Comment by Yurlungur** [comment]
Resolved by #439
