### ISSUE TITLE
sesame2spiner should handle material names

### ISSUE THREAD

**Issue by Yurlungur** [lanl/singularity-eos#47]
There should be a way to handle sesame files with missing or duplicate material names. Issue found by @dholladay00

**Comment by jhp-lanl** [comment]
What exactly is the issue? Is it the material naming on the `sesame2spiner` side or is it a sesame issue?

**Comment by Yurlungur** [comment]
So the way `sesame2spiner` works, is it utilizes both matid and a more human readable name. It adds the matid as a group in the hdf5 file and the material name is a symbolic link to the ID. Ut first defers to the user input for a custom name. (This can be set in the input deck.) If no name is specified by the user, it defaults to the name in the table. Most tables have a name in the metadata. But not all. And some matids are for the same material... just different iterations. 

The problem is: if the user doesn't specify something, and two of the materials that `sesame2spiner` is outputting to an sp5 file have the same name, which can happen, it currently produces a cryptic HDF5 error. Better would be to handle this automatically, or at least spit out a more meaningful error message.

**Comment by jhp-lanl** [comment]
Agreed. For the most part I think somebody will only want two EOS for the same material for testing purposes, but it's a common test so a good idea to handle.

**Comment by Yurlungur** [comment]
It should be an easy change. I just need to sit down and try it out.
