### ISSUE TITLE
Weird issue with kokkos kernels in spackage

### ISSUE THREAD

**Issue by Yurlungur** [lanl/singularity-eos#62]
Build fails on x86-volta node. Experimentation with @dholladay00 and @mauneyc-LANL shows build is fixed if the `kokkos-kernels` is set to `~shared built_type=Debug`. Not clear if problem is in kokkos, spack, or with the node configuration.

**Comment by dholladay00** [comment]
can this be closed?

**Comment by Yurlungur** [comment]
Yes.
