### ISSUE TITLE
Are guards needed for wrong template parameter passed to `EosBase`?

### ISSUE THREAD

**Issue by jhp-lanl** [lanl/singularity-eos#95]
Do we need to add something like this to the `EosBase` class in order to make sure the compiler knows to throw an error if the wrong template parameter is used?

```c++
template <typename T>
class Base
{
public:
    // ...
private:
    Base(){};
    friend T;
};
```

**Comment by Yurlungur** [comment]
It's not obvious to me how to make such a guard... but perhaps we should delete the default constructor, so the base class can't be initialized on its own?

**Comment by jhp-lanl** [comment]
> It's not obvious to me how to make such a guard... but perhaps we should delete the default constructor, so the base class can't be initialized on its own?

Well, this was the guard suggested when I did some more reading about the CRTP. Basically this guards against the inheriting class being different from the CRTP template argument as I understand it. I believe the compiler will barf on `friend T` because T is not a child class of the parent CRTP class even though it's the template parameter.

The main thing I need to test is what happens when you accidentally do that and what happens. If it's a sensible compiler error, then it's not needed. But if it's something impenetrable, this might save somebody a lot of stress in the future.

**Comment by Yurlungur** [comment]
Huh I don't fully understand that. I do notice that the default constructor being private probably does what I was suggesting. I think having the default constructor be deleted or private is probably enough: If there's no way to construct the base class, then the only way to use it is to inherit from it.

**Comment by jhp-lanl** [comment]
Yeah sorry, you're right. The fact that the constructor is private I guess is the key. I'll have to read up on C++ inheritance and constructors to make sure I understand whether the `friend` is needed or not.
